import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { Navbarlogo } from "@/components/navbar/navbar.logo";
import { Navbar } from "@/components/navbar/navbar";
import FooterDemo from "@/components/Footer/footer"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Hacfy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${poppins.variable} antialiased bg-primary scroll-smooth`}
      >
       <div className="flex flex-col min-h-screen">
      <Navbarlogo/>
      <main className="flex-1 overflow-y-auto">
    
        
        {children}
        </main>
        </div>
        <FooterDemo />
      </body>
    </html>
  );
}